### ISSUE TITLE
#movingtogitlab

### ISSUE THREAD

**Issue by aalok-sathe** [theshorttamperedclavier/theshorttamperedclavier.github.io#11]
should we?

- [X] set up a new [GitLab repo](https://gitlab.com/the-short-tampered-clavier/)
- [ ] deploy to GL pages
    - [X] test [deploy](https://the-short-tampered-clavier.gitlab.io/)
     - [ ] fix page style
- [ ]  set up accounts and provide access
- [x] set up CI for GL pages [![pipeline status](https://gitlab.com/the-short-tampered-clavier/the-short-tampered-clavier.gitlab.io/badges/master/pipeline.svg)](https://gitlab.com/the-short-tampered-clavier/the-short-tampered-clavier.gitlab.io/commits/master)
- [ ] test with new content
- [ ] test functioning of comments

**Comment by mjuvekar7** [comment]
IMO we shouldn't. It works well as it is. If things start going south on the GH front we can always jump ship then.

**Comment by mjuvekar7** [comment]
This seems like an overreaction

**Comment by aalok-sathe** [comment]
I think if you give GL a try you'll really like it

**Comment by mjuvekar7** [comment]
I have used gitlab, and it's nice. But there's no foodt reason to port over right now other than the remote possibility of GitHub doing wired stuff in the future
