### ISSUE TITLE
Not enough content!

### ISSUE THREAD

**Issue by shardulc** [theshorttamperedclavier/theshorttamperedclavier.github.io#19]
We haven't been generating enough content for the blog *at all*. Very sad. During the semester we are all busy but I think it's worth getting some thoughts up here in summer break. (And commit to doing so in other breaks too.) Let us write things.

**Comment by mjuvekar7** [comment]
Very motivate

**Comment by aalok-sathe** [comment]
I was able to replicate this issue on my end.
